### ISSUE TITLE
Controller User

### ISSUE THREAD

**Issue by EdwinClaudeHES** [HE-Arc/SettlePlan#10]
Modification du controller User.
Ajout de la gestion de demande d'amis

**Comment by EdwinClaudeHES** [comment]
Changement de l'assignation, cette tâche est donné à Edwin Claude. Ce changement a été fait, car le comportement du controller de file n'est pas encore totalement défini.

**Comment by ErgunKilic** [comment]
Petit problème sur la page users/friends, tu avais oublier de set la variable "$friendsAccepted" à null.
J'ai fait la correction.

**Comment by VincentRubin** [comment]
Vérifier avec le groupe au complet.
