### ISSUE TITLE
Controller Task

### ISSUE THREAD

**Issue by EdwinClaudeHES** [HE-Arc/SettlePlan#8]
Création du controller de la table Task.
Ajout de la gestion CRUD.

**Comment by VincentRubin** [comment]
La création d'une nouvelle tâche subit une erreur concernant l'ajout de fichier si il n'y en a pas.

**Comment by ErgunKilic** [comment]
C'est corriger en ajoutant un if pour vérifier le champs

**Comment by VincentRubin** [comment]
Vérifier avec le groupe au complet. 

Les fichiers sont gérés avec les tâches en 1:n. Une tâche peut avoir plusieurs fichiers, mais un fichier n'a qu'une seule tâche. A l'origine, il était prévue qu'une relation n:m soit utilisé afin de diminuer la place utiliser par les fichiers sur le serveur. Celà n'a pas été fait par manque de temps. L'importation n'importe pas les fichiers puisque la méthode originellement prévue n'a pas été terminer.
