### ISSUE TITLE
Controller File

### ISSUE THREAD

**Issue by EdwinClaudeHES** [HE-Arc/SettlePlan#9]
Création du controller pour la table File.
Ajout de la gestion CRUD.

**Comment by EdwinClaudeHES** [comment]
Problème de récupération du fichier de la vue au controller. $files = $request->file('file'). La variable $files est toujours null

**Comment by EdwinClaudeHES** [comment]
![image](https://user-images.githubusercontent.com/48317178/70862760-b992e000-1f40-11ea-82c3-6316a102f21b.png)

**Comment by EdwinClaudeHES** [comment]
> Problème de récupération du fichier de la vue au controller. $files = $request->file('file'). La variable $files est toujours null

Problème résolu. Il fallait ajouter un paramètre au formulaire : enctype="multipart/form-data"

**Comment by EdwinClaudeHES** [comment]
> Problème avec la table de liaison entre file et task.
> 
> ![image](https://user-images.githubusercontent.com/48317178/70862760-b992e000-1f40-11ea-82c3-6316a102f21b.png)

Résolution du problème, en faisant une nouvelle migration en changeant le nom de la table "tasks_has_files".

**Comment by VincentRubin** [comment]
Vérifier avec le groupe au complet. 

La gestion des fichiers est opérée dans le Controller Task donc ce controller n'a pas son propre fichier.
